CREATE DATABASE Treinamento_ProLogos;

USE Treinamento_ProLogos;

CREATE TABLE PRODUTOS (
    ID BIGINT PRIMARY KEY IDENTITY,
    CODIGO VARCHAR(14),
    DESCRICAO VARCHAR(255),
    SALDO_ESTOQUE DECIMAL(18,2),
    VALOR_COMPRA DECIMAL(18,2),
    VALOR_VENDA DECIMAL(18,2),
    DATA_CADASTRO DATETIME2,
    ATIVO BIT,
    TIPO_PRODUTO INT,
    MARCA_ID BIGINT,
    GRUPO_PRODUTO_ID BIGINT
);

CREATE TABLE GRUPOS_PRODUTOS (
    ID BIGINT PRIMARY KEY IDENTITY,
    NOME VARCHAR(50),
    DESCRICAO VARCHAR(255),
    DATA_CADASTRO DATETIME2
);

CREATE TABLE MARCAS (
    ID BIGINT PRIMARY KEY IDENTITY,
    NOME VARCHAR(50),
    SEGMENTO VARCHAR(255),
    DATA_CADASTRO DATETIME2
);